version: '3'
services: 
    frontend:
        container_name: docker-node-mongo-react-frontend
        restart: always
        build: ./client
        ports: 
            - '3000:3000'
        links: 
            - app
    app:
        container_name: docker-node-mongo-react
        restart: always
        build: ./server
        ports: 
            - '4000:4000'
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'